server:
  port: 8080

spring:
  #静态文件请求匹配方式
  mvc:
    static-path-pattern: /**
  #修改默认的静态寻址资源目录
  resources:
    static-locations: classpath:/templates/,classpath:/resources/,classpath:/static/
  thymeleaf:
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: microservice-consumer

eureka:
  client:
    register-with-eureka: true
    service-url: 
      defaultZone: http://localhost:6001/eureka/
  instance:
    instance-id: microservice-consumer-8080
    prefer-ip-address: true     #访问路径可以显示IP地址

#注释后hystrix服务降级不可用
#feign:
#  hystrix:
#    enabled: true